INSERT /*+ :hints */ INTO bill_error_detail (bill_id,
                                             bill_ln_id,
                                             code,
                                             reason,
                                             stack_trace,
                                             cre_dttm,
                                             partition_id,
                                             ilm_dt,
                                             ilm_arch_sw,
                                             batch_code,
                                             batch_attempt)
VALUES (:bill_id,
        :bill_ln_id,
        :code,
        :reason,
        :stack_trace,
        SYSTIMESTAMP,
        :partition_id,
        :ilm_dt,
        'Y',
        :batch_code,
        :batch_attempt)