CREATE OR REPLACE VIEW vw_payment_request
AS
SELECT b.bill_id                               AS bill_id,
       b.party_id                              AS per_id_nbr,
       SUBSTR(b.lcp, -LEAST(LENGTH(b.lcp), 5)) AS cis_division,
       '1'                                     AS line_id,
       b.bill_nbr                              AS alt_bill_id,
       b.bill_dt                               AS bill_dt,
       b.acct_type                             AS acct_type,
       decode(sign(b.bill_amt + NVL(pba.amount, 0)), 1, 'DR', 'CR') AS pay_type,
       b.bill_amt + NVL(pba.amount, 0)         AS bill_amt,
       b.currency_cd                           AS currency_cd,
       b.individual_bill                       AS is_ind_flg,
       b.sett_sub_lvl_type                     AS sub_stlmnt_lvl,
       b.sett_sub_lvl_val                      AS sub_stlmnt_lvl_ref,
       NULL                                    AS cr_note_fr_bill_id,
       b.adhoc_bill_flg                        AS is_imd_fin_adj,
       b.manual_narrative                      AS fin_adj_man_nrt,
       b.rel_reserve_flg                       AS rel_rsrv_flg,
       b.rel_waf_flg                           AS rel_waf_flg,
       b.fastest_pay_route                     AS fastest_route_indicator,
       b.case_id                               AS case_identifier,
       REGEXP_REPLACE(REGEXP_REPLACE(granularity_key_val, '(\|)[^,]+$', ''), '(\|)[^,]+,','|')
                         AS pay_req_granularities,
       b.cre_dttm                              AS create_dttm,
       b.cre_dttm                              AS upload_dttm,
       'Y'                                     AS extract_flg,
       NULL                                    AS extract_dttm,
       NULL                                    AS reuse_due_dt,
       NULL                                    AS inv_recalc_flg,
       b.ilm_dt                                AS ilm_dt,
       b.ilm_arch_sw                           AS ilm_arch_sw,
       NULL                                    AS pay_req_id,
       'MPG'                                   AS mpg_type,
       b.granularity                           AS sett_level_granularity,
       b.settlement_region_id                  AS settlement_region_id,
       NULL                                    AS overpayment_flg,
       1                                       AS pay_detail_id
FROM vw_bill b
         LEFT JOIN
     vw_post_bill_adj pba ON b.bill_id = pba.bill_id
WHERE b.prev_bill_id IS NULL
  AND (b.debt_mig_type IS NULL OR b.debt_mig_type <> 'MIG_DEBT')

UNION ALL
SELECT bill_id,
       per_id_nbr,
       cis_division,
       TRIM(line_id) AS line_id,
       alt_bill_id,
       bill_dt,
       acct_type,
       pay_type,
       bill_amt,
       currency_cd,
       is_ind_flg,
       sub_stlmnt_lvl,
       sub_stlmnt_lvl_ref,
       cr_note_fr_bill_id,
       is_imd_fin_adj,
       fin_adj_man_nrt,
       rel_rsrv_flg,
       rel_waf_flg,
       fastest_route_indicator,
       case_identifier,
       pay_req_granularities,
       create_dttm,
       upload_dttm,
       extract_flg,
       extract_dttm,
       reuse_due_dt,
       inv_recalc_flg,
       ilm_dt,
       ilm_arch_sw,
       pay_req_id,
       mpg_type,
       sett_level_granularity,
       settlement_region_id,
       overpayment_flg,
       pay_detail_id
FROM CM_PAY_REQ_OVERPAY;