BEGIN
    EXECUTE IMMEDIATE 'RENAME CM_INVOICE_DATA_BAK TO CM_INVOICE_DATA ';
    EXECUTE IMMEDIATE 'RENAME CM_INVOICE_DATA_LN_BAK TO CM_INVOICE_DATA_LN';
    EXECUTE IMMEDIATE 'RENAME CM_INV_DATA_LN_BCL_BAK TO CM_INV_DATA_LN_BCL';
    EXECUTE IMMEDIATE 'RENAME CM_INV_DATA_LN_RATE_BAK TO CM_INV_DATA_LN_RATE';
    EXECUTE IMMEDIATE 'RENAME CM_INV_DATA_LN_SVC_QTY_BAK TO CM_INV_DATA_LN_SVC_QTY';
    EXECUTE IMMEDIATE 'RENAME CM_INV_DATA_TAX_BAK TO CM_INV_DATA_TAX';
    EXECUTE IMMEDIATE 'RENAME CM_INV_DATA_ADJ_BAK TO CM_INV_DATA_ADJ';
    EXECUTE IMMEDIATE 'RENAME CM_INV_DATA_EXCP_BAK TO CM_INV_DATA_EXCP';
    EXECUTE IMMEDIATE 'RENAME CM_PAY_REQ_BAK TO CM_PAY_REQ';
    EXECUTE IMMEDIATE 'RENAME CM_PAY_REQ_GRANULARITIES_BAK TO CM_PAY_REQ_GRANULARITIES';
    EXECUTE IMMEDIATE 'RENAME CM_NON_TRANS_PRICE_BAK TO CM_NON_TRANS_PRICE';
    EXECUTE IMMEDIATE 'RENAME CM_BILL_ID_MAP_BAK TO CM_BILL_ID_MAP';

    EXECUTE IMMEDIATE 'CREATE SYNONYM ODI_WORK.CM_INVOICE_DATA FOR CISADM.CM_INVOICE_DATA';
    EXECUTE IMMEDIATE 'CREATE SYNONYM ODI_WORK.CM_INVOICE_DATA_LN FOR CISADM.CM_INVOICE_DATA_LN';
    EXECUTE IMMEDIATE 'CREATE SYNONYM ODI_WORK.CM_INV_DATA_LN_BCL FOR CISADM.CM_INV_DATA_LN_BCL';
    EXECUTE IMMEDIATE 'CREATE SYNONYM ODI_WORK.CM_INV_DATA_LN_RATE FOR CISADM.CM_INV_DATA_LN_RATE';
    EXECUTE IMMEDIATE 'CREATE SYNONYM ODI_WORK.CM_INV_DATA_LN_SVC_QTY FOR CISADM.CM_INV_DATA_LN_SVC_QTY';
    EXECUTE IMMEDIATE 'CREATE SYNONYM ODI_WORK.CM_INV_DATA_TAX FOR CISADM.CM_INV_DATA_TAX';
    EXECUTE IMMEDIATE 'CREATE SYNONYM ODI_WORK.CM_INV_DATA_ADJ FOR CISADM.CM_INV_DATA_ADJ';
    EXECUTE IMMEDIATE 'CREATE SYNONYM ODI_WORK.CM_INV_DATA_EXCP FOR CISADM.CM_INV_DATA_EXCP';
    EXECUTE IMMEDIATE 'CREATE SYNONYM ODI_WORK.CM_PAY_REQ FOR CISADM.CM_PAY_REQ';
    EXECUTE IMMEDIATE 'CREATE SYNONYM ODI_WORK.CM_PAY_REQ_GRANULARITIES FOR CISADM.CM_PAY_REQ_GRANULARITIES';
    EXECUTE IMMEDIATE 'CREATE SYNONYM IF112_DBLINK_APPUSER.CM_NON_TRANS_PRICE FOR CISADM.CM_NON_TRANS_PRICE';
    EXECUTE IMMEDIATE 'CREATE SYNONYM IF112_DBLINK_APPUSER.CM_BILL_ID_MAP FOR CISADM.CM_BILL_ID_MAP';

EXCEPTION
    WHEN OTHERS THEN
        IF sqlcode != -04043 THEN
            RAISE;
        END IF;

END;
/

