CREATE TABLE payment_request_overpayment
(
    bill_id                     VARCHAR2(64)   NOT NULL ENABLE,
    per_id_nbr                  VARCHAR2(16)   NOT NULL ENABLE,
    cis_division                CHAR(5)        NOT NULL ENABLE,
    line_id                     CHAR(12)       NOT NULL ENABLE,
    alt_bill_id                 VARCHAR2(30)   NOT NULL ENABLE,
    bill_dt                     DATE           NOT NULL ENABLE,
    acct_type                   VARCHAR2(4)    NOT NULL ENABLE,
    pay_type                    CHAR(2)        NOT NULL ENABLE,
    bill_amt                    NUMBER(14,2)   NOT NULL ENABLE,
    currency_cd                 CHAR(3)        NOT NULL ENABLE,
    is_ind_flg                  CHAR(1)        NOT NULL ENABLE,
    sub_stlmnt_lvl              VARCHAR2(60)                  ,
    sub_stlmnt_lvl_ref          VARCHAR2(60)                  ,
    cr_note_fr_bill_id          CHAR(12)                      ,
    is_imd_fin_adj              CHAR(1)        NOT NULL ENABLE,
    fin_adj_man_nrt             VARCHAR2(18)   NOT NULL ENABLE,
    rel_rsrv_flg                CHAR(1)        NOT NULL ENABLE,
    rel_waf_flg                 CHAR(1)                       ,
    fastest_route_indicator     VARCHAR2(10)   NOT NULL ENABLE,
    case_identifier             VARCHAR2(30)   NOT NULL ENABLE,
    pay_req_granularities       VARCHAR2(60)                  ,
    create_dttm                 DATE           NOT NULL ENABLE,
    upload_dttm                 DATE           NOT NULL ENABLE,
    extract_flg                 CHAR(1)        NOT NULL ENABLE,
    extract_dttm                DATE                          ,
    reuse_due_dt                CHAR(1)                       ,
    inv_recalc_flg              CHAR(1)                       ,
    ilm_dt                      DATE                          ,
    ilm_arch_sw                 CHAR(1)        DEFAULT 'N'    ,
    pay_req_id                  CHAR(24)       DEFAULT ' '    ,
    mpg_type                    VARCHAR2(4)                   ,
    pay_detail_id               NUMBER(15,0)   DEFAULT 0      ,
    overpayment_flg             VARCHAR2(1)    DEFAULT null   ,
    sett_level_granularity      VARCHAR2(60)   DEFAULT ' '    ,
    settlement_region_id        VARCHAR2(30)                  ,
    CONSTRAINT pay_req_op_pk PRIMARY KEY (bill_id, line_id, pay_detail_id)
    )
    PARTITION BY RANGE (ilm_dt) INTERVAL (NUMTODSINTERVAL(1,'DAY'))
(PARTITION P0  VALUES LESS THAN (TO_DATE(' 2021-04-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')));