MERGE /*+ :insert-hints */ INTO cm_bill_payment_dtl_snapshot s
USING (SELECT * FROM post_bill_adj_accounting
       WHERE batch_code = :batch_code
       AND batch_attempt = :batch_attempt
       AND ilm_dt = :ilm_dt
       AND sub_acct_type = 'FUND') b
ON (b.bill_id = s.bill_id AND s.line_id = '1')
WHEN MATCHED THEN
    UPDATE SET  s.prev_unpaid_amt = b.bill_amt,
                s.latest_pay_amt = b.amount,
                s.unpaid_amt = b.bill_amt + b.amount,
                s.bill_balance = b.bill_amt + b.amount,
                s.latest_status =  'WAF',
                s.latest_pay_dtl_id = (SELECT max(pay_dtl_id) from cm_bill_payment_dtl where bill_id = b.bill_id and line_id = '1' and status_cd ='WAF')

WHEN NOT MATCHED THEN
    INSERT (bill_balance_id,
            latest_pay_dtl_id,
            latest_upload_dttm,
            pay_dt,
            bill_dt,
            party_id,
            lcp_description,
            lcp,
            acct_type,
            account_description,
            ext_transmit_id,
            bill_id,
            alt_bill_id,
            line_id,
            line_amt,
            prev_unpaid_amt,
            latest_pay_amt,
            unpaid_amt,
            bill_amount,
            bill_balance,
            currency_cd,
            latest_status,
            pay_type,
            ilm_dt,
            ilm_arch_sw,
            overpaid,
            record_stat,
            status_upd_dttm,
            message_cat_nbr,
            message_nbr,
            error_info,
            ext_source_cd,
            credit_note_id
    )
    VALUES (bill_balance_id_seq.nextval,
            (SELECT max(pay_dtl_id) from cm_bill_payment_dtl where bill_id = b.bill_id and line_id = '1' and status_cd ='WAF'),
            SYSDATE,
            trunc(SYSDATE),
            b.bill_dt,
            b.party_id,
            b.lcp,
            b.lcp,
            b.acct_type,
            'Funding',
            b.post_bill_adj_id,
            b.bill_id,
            (SELECT bill_nbr FROM vw_bill WHERE bill_id = b.bill_id),
            '1',
            b.bill_amt,
            b.bill_amt,
            b.amount,
            b.bill_amt + b.amount,
            b.bill_amt,
            b.bill_amt + b.amount,
            b.currency_cd,
            'WAF',
            DECODE(SIGN(b.bill_amt), 1, 'DR', 'CR'),
            b.cre_dttm,
            'Y',
            null,
            'PENDING',
            null,
            0,
            0,
            ' ',
            ' ',
            null
    )