SELECT /*+ :hints */
    bill_id              AS billId,
    bill_nbr             AS billNumber,
    party_id             AS partyId,
    bill_sub_acct_id     AS billSubAccountId,
    tariff_type          AS tariffType,
    template_type        AS templateType,
    lcp                  AS legalCounterparty,
    acct_type            AS accountType,
    account_id           AS accountId,
    business_unit        AS businessUnit,
    bill_dt              AS billDate,
    bill_cyc_id          AS billCycleId,
    start_dt             AS startDate,
    end_dt               AS endDate,
    currency_cd          AS currencyCode,
    bill_amt             AS billAmount,
    bill_ref             AS billReference,
    status               AS status,
    adhoc_bill_flg       AS adhocBillFlag,
    sett_sub_lvl_type    AS settlementSubLevelType,
    sett_sub_lvl_val     AS settlementSubLevelValue,
    granularity          AS granularity,
    granularity_key_val  AS granularityKeyValue,
    rel_waf_flg          AS releaseWafIndicator,
    rel_reserve_flg      AS releaseReserveIndicator,
    fastest_pay_route    AS fastestPaymentRouteIndicator,
    case_id              AS caseId,
    individual_bill      AS individualBillIndicator,
    manual_narrative     AS manualNarrative,
    settlement_region_id AS processingGroup,
    prev_bill_id         AS previousBillId,
    debt_dt              AS debtDate,
    debt_mig_type        AS debtMigrationType,
    partition_id         AS partitionId
FROM vw_bill
WHERE ilm_dt >= :low
  AND ilm_dt < :high