with STG_298_CM_INVOICE_DATA as (
    select
    'NRML' as REC_TYPE,
    null as BILL_ID
    from dual
)
select
	CM_INV_DATA_TAX.BILL_ID	C1_BILL_ID,
	CM_INV_DATA_TAX.CALC_AMT	C2_CALC_AMT,
	CM_INV_DATA_TAX.BASE_AMT	C3_BASE_AMT,
	CM_INV_DATA_TAX.TAX_STAT	C4_TAX_STAT,
	CM_INV_DATA_TAX.TAX_STAT_DESCR	C5_TAX_STAT_DESCR,
	CM_INV_DATA_TAX.TAX_RATE	C6_TAX_RATE,
	CM_INV_DATA_TAX.ILM_DT	C7_UPLOAD_DTTM,
	CM_INV_DATA_TAX.EXTRACT_FLG	C8_EXTRACT_FLG,
	CM_INV_DATA_TAX.EXTRACT_DTTM	C9_EXTRACT_DTTM
from	ODI_WORK.CM_INV_DATA_TAX   CM_INV_DATA_TAX, STG_298_CM_INVOICE_DATA   STG_CM_INVOICE_DATA
where	(1=1)
And (CM_INV_DATA_TAX.EXTRACT_FLG='Y')
 And (CM_INV_DATA_TAX.ILM_DT  >= TO_DATE( :startDate,'YYYY/MM/DD HH24:MI:SS') AND
CM_INV_DATA_TAX.ILM_DT  < TO_DATE( :endDate,'YYYY/MM/DD HH24:MI:SS') )
 And (STG_CM_INVOICE_DATA.REC_TYPE = 'NRML')
 And (CM_INV_DATA_TAX.BILL_ID=STG_CM_INVOICE_DATA.BILL_ID)
