with STG_298_CM_INVOICE_DATA as (
    select
    'NRML' as REC_TYPE,
    null as BILL_ID
    from dual
)
select
/*+ ENABLE_PARALLEL_DML PARALLEL(16) */

	CM_INVOICE_DATA_LN.BILL_ID BILL_ID,
	CM_INVOICE_DATA_LN.BSEG_ID BSEG_ID,
	CM_INVOICE_DATA_LN.BILLING_PARTY_ID BILLING_PARTY_ID,
	CM_INVOICE_DATA_LN.PRICE_CATEGORY PRICE_CATEGORY,
	CM_INVOICE_DATA_LN.PRICE_CATEGORY_DESCR PRICE_CATEGORY_DESCR,
	CM_INVOICE_DATA_LN.CURRENCY_CD CURRENCY_CD,
	CM_INVOICE_DATA_LN.ILM_DT UPLOAD_DTTM,
	CM_INVOICE_DATA_LN.EXTRACT_FLG EXTRACT_FLG,
	CM_INVOICE_DATA_LN.EXTRACT_DTTM EXTRACT_DTTM,
	STG_CM_INVOICE_DATA.REC_TYPE REC_TYPE
from	ODI_WORK.CM_INVOICE_DATA_LN   CM_INVOICE_DATA_LN, STG_298_CM_INVOICE_DATA   STG_CM_INVOICE_DATA
where		(1=1)
 And (CM_INVOICE_DATA_LN.BILL_ID = STG_CM_INVOICE_DATA.BILL_ID)
And (CM_INVOICE_DATA_LN.ILM_DT  >= TO_DATE( :startDate,'YYYY/MM/DD HH24:MI:SS')
AND CM_INVOICE_DATA_LN.ILM_DT  < TO_DATE( :endDate,'YYYY/MM/DD HH24:MI:SS'))
 And (STG_CM_INVOICE_DATA.REC_TYPE = 'NRML')
