select
	CM_INVOICE_DATA.BILL_ID    BILL_ID,	CM_INVOICE_DATA.ALT_BILL_ID    ALT_BILL_ID,	CM_INVOICE_DATA.BILLING_PARTY_ID    BILLING_PARTY_ID,	CM_INVOICE_DATA.CIS_DIVISION    CIS_DIVISION,	CM_INVOICE_DATA.WPBU    WPBU,	CM_INVOICE_DATA.BILL_DT    BILL_DT,	CM_INVOICE_DATA.BILL_CYC_CD    BILL_CYC_CD,	CM_INVOICE_DATA.WIN_START_DT    WIN_START_DT,	CM_INVOICE_DATA.WIN_END_DT    WIN_END_DT,	CM_INVOICE_DATA.CURRENCY_CD    CURRENCY_CD,	CM_INVOICE_DATA.CALC_AMT    CALC_AMT,	CM_INVOICE_DATA.MERCH_TAX_REG_NBR    MERCH_TAX_REG_NBR,	CM_INVOICE_DATA.WP_TAX_REG_NBR    WP_TAX_REG_NBR,	CM_INVOICE_DATA.TAX_AUTHORITY    TAX_AUTHORITY,	CM_INVOICE_DATA.TAX_TYPE    TAX_TYPE,	CM_INVOICE_DATA.PREVIOUS_AMT    PREVIOUS_AMT,	CM_INVOICE_DATA.CR_NOTE_FR_BILL_ID    CR_NOTE_FR_BILL_ID,	CM_INVOICE_DATA.ILM_DT    UPLOAD_DTTM,	CM_INVOICE_DATA.EXTRACT_FLG    EXTRACT_FLG,	CM_INVOICE_DATA.EXTRACT_DTTM    EXTRACT_DTTM,	CM_INVOICE_DATA.ACCT_TYPE    ACCT_TYPE,	'NRML'    REC_TYPE
from	ODI_WORK.CM_INVOICE_DATA   CM_INVOICE_DATA
where	(1=1)

And (CM_INVOICE_DATA.EXTRACT_FLG = 'Y'
AND CM_INVOICE_DATA.ILM_DT >= TO_DATE( :startDate,'YYYY/MM/DD HH24:MI:SS')
AND CM_INVOICE_DATA.ILM_DT < TO_DATE( :endDate,'YYYY/MM/DD HH24:MI:SS'))

UNION ALL
select
	CM_INVOICE_DATA.BILL_ID    BILL_ID,	CM_INVOICE_DATA.ALT_BILL_ID    ALT_BILL_ID,	CM_INVOICE_DATA.BILLING_PARTY_ID    BILLING_PARTY_ID,	CM_INVOICE_DATA.CIS_DIVISION    CIS_DIVISION,	CM_INVOICE_DATA.WPBU    WPBU,	CM_INVOICE_DATA.BILL_DT    BILL_DT,	CM_INVOICE_DATA.BILL_CYC_CD    BILL_CYC_CD,	CM_INVOICE_DATA.WIN_START_DT    WIN_START_DT,	CM_INVOICE_DATA.WIN_END_DT    WIN_END_DT,	CM_INVOICE_DATA.CURRENCY_CD    CURRENCY_CD,	CM_INVOICE_DATA.CALC_AMT    CALC_AMT,	CM_INVOICE_DATA.MERCH_TAX_REG_NBR    MERCH_TAX_REG_NBR,	CM_INVOICE_DATA.WP_TAX_REG_NBR    WP_TAX_REG_NBR,	CM_INVOICE_DATA.TAX_AUTHORITY    TAX_AUTHORITY,	CM_INVOICE_DATA.TAX_TYPE    TAX_TYPE,	CM_INVOICE_DATA.PREVIOUS_AMT    PREVIOUS_AMT,	CM_INVOICE_DATA.CR_NOTE_FR_BILL_ID    CR_NOTE_FR_BILL_ID,	CM_INVOICE_DATA.ILM_DT    UPLOAD_DTTM,	CM_INVOICE_DATA.EXTRACT_FLG    EXTRACT_FLG,	CM_INVOICE_DATA.EXTRACT_DTTM    EXTRACT_DTTM,	CM_INVOICE_DATA.ACCT_TYPE    ACCT_TYPE,	'EXCP'    REC_TYPE
from	ODI_WORK.CM_INVOICE_DATA   CM_INVOICE_DATA, ODI_WORK.CM_INV_DATA_EXCP   CM_INV_DATA_EXCP
where	(1=1)
 And (CM_INVOICE_DATA.BILL_ID=CM_INV_DATA_EXCP.BILL_ID)
And (CM_INV_DATA_EXCP.FIX_DT >= TO_DATE( :startDate,'YYYY/MM/DD HH24:MI:SS')
AND CM_INV_DATA_EXCP.FIX_DT < TO_DATE( :endDate,'YYYY/MM/DD HH24:MI:SS'))