with STG_298_CM_INVOICE_DATA_LN as (
    select
    'NRML' as REC_TYPE,
    null as BILL_ID,
    null as BSEG_ID
    from dual
)
select /*+ ENABLE_PARALLEL_DML PARALLEL(CM_INV_DATA_LN_SVC_QTY) APPEND */
	CM_INV_DATA_LN_SVC_QTY.BILL_ID	C1_BILL_ID,
	CM_INV_DATA_LN_SVC_QTY.BSEG_ID	C2_BSEG_ID,
	CM_INV_DATA_LN_SVC_QTY.SQI_CD	C3_SQI_CD,
	CM_INV_DATA_LN_SVC_QTY.SVC_QTY	C4_SVC_QTY,
	CM_INV_DATA_LN_SVC_QTY.SQI_DESCR	C5_SQI_DESCR,
	CM_INV_DATA_LN_SVC_QTY.ILM_DT	C6_UPLOAD_DTTM,
	CM_INV_DATA_LN_SVC_QTY.EXTRACT_FLG	C7_EXTRACT_FLG,
	CM_INV_DATA_LN_SVC_QTY.EXTRACT_DTTM	C8_EXTRACT_DTTM
from	ODI_WORK.CM_INV_DATA_LN_SVC_QTY   CM_INV_DATA_LN_SVC_QTY, STG_298_CM_INVOICE_DATA_LN   STG_CM_INVOICE_DATA_LN
where	(1=1)
And (CM_INV_DATA_LN_SVC_QTY.ILM_DT   >= TO_DATE( :startDate,'YYYY/MM/DD HH24:MI:SS') AND
CM_INV_DATA_LN_SVC_QTY.ILM_DT   < TO_DATE( :endDate,'YYYY/MM/DD HH24:MI:SS')
)
 And (STG_CM_INVOICE_DATA_LN.REC_TYPE = 'NRML')

 And (CM_INV_DATA_LN_SVC_QTY.BILL_ID=STG_CM_INVOICE_DATA_LN.BILL_ID AND CM_INV_DATA_LN_SVC_QTY.BSEG_ID=STG_CM_INVOICE_DATA_LN.BSEG_ID)
