SELECT /*+ :hints */
    bill_id                        AS billId,
    party_id                       AS partyId,
    lcp                            AS legalCounterpartyId,
    acct_id                        AS accountId,
    bill_sub_acct_id               AS billSubAccountId,
    acct_type                      AS accountType,
    business_unit                  AS businessUnit,
    bill_cyc_id                    AS billCycleId,
    start_dt                       AS scheduleStart,
    end_dt                         AS scheduleEnd,
    currency_cd                    AS currency,
    bill_ref                       AS billReference,
    adhoc_bill                     AS adhocBillIndicator,
    sett_sub_lvl_type              AS settlementSubLevelType,
    sett_sub_lvl_val               AS settlementSubLevelValue,
    granularity                    AS granularity,
    granularity_key_val            AS granularityKeyValue,
    debt_dt                        AS debtDate,
    debt_mig_type                  AS debtMigrationType,
    overpayment_flg                AS overpaymentIndicator,
    rel_waf_flg                    AS releaseWAFIndicator,
    rel_reserve_flg                AS releaseReserveIndicator,
    fastest_pay_route              AS fastestPaymentRouteIndicator,
    case_id                        AS caseIdentifier,
    individual_bill                AS individualBillIndicator,
    manual_narrative               AS manualBillNarrative,
    miscalculation_flag            AS miscalculationFlag,
    CAST(first_failure_on AS DATE) AS firstFailureOn,
    retry_count                    AS retryCount,
    partition_id                   AS partitionId
FROM vw_pending_bill_s