CREATE TABLE BILLABLE_CHARGE_SERVICE_OUTPUT
   (BILLABLE_ITEM_ID VARCHAR2(64),
	BILLABLE_CHARGE_ID VARCHAR2(12),
	SQI_CD VARCHAR2(12),
	RATE_SCHEDULE VARCHAR2(8),
	SVC_QTY NUMBER(36,18),
	BATCH_CODE VARCHAR2(128) NOT NULL,
	BATCH_ATTEMPT NUMBER(3,0) NOT NULL,
	PARTITION_ID NUMBER(*,0) NOT NULL,
	ILM_DT TIMESTAMP (6) NOT NULL,
	ILM_ARCH_SW CHAR(1) NOT NULL,
	PARTITION NUMBER(5,0) GENERATED ALWAYS AS (ORA_HASH(BILLABLE_ITEM_ID,127)) VIRTUAL
   );