CREATE TABLE BILLABLE_CHARGE_LINE
   (BILLABLE_ITEM_ID VARCHAR2(64),
	BILLABLE_CHARGE_ID CHAR(12),
	LINE_SEQUENCE NUMBER(3,0),
	CHARGE_AMOUNT NUMBER(15,2),
	CURRENCY_CD CHAR(3),
	DISTRIBUTION_ID CHAR(10),
	PRECISE_CHARGE_AMOUNT NUMBER(36,18),
	BATCH_CODE VARCHAR2(128) NOT NULL ,
	BATCH_ATTEMPT NUMBER(3,0) NOT NULL ,
	PARTITION_ID NUMBER(*,0) NOT NULL ,
	ILM_DT TIMESTAMP (6) NOT NULL ,
	ILM_ARCH_SW CHAR(1) NOT NULL ,
	DESCRIPTION_ON_BILL VARCHAR2(80),
	CHARACTERISTIC_VALUE CHAR(16),
	PARTITION NUMBER(5,0) GENERATED ALWAYS AS (ORA_HASH(BILLABLE_ITEM_ID,127)) VIRTUAL ,
	RATE NUMBER(36,18),
	RATE_TYPE CHAR(6)
   );