BEGIN
    EXECUTE IMMEDIATE 'RENAME CM_INVOICE_DATA TO CM_INVOICE_DATA_BAK';
    EXECUTE IMMEDIATE 'RENAME CM_INVOICE_DATA_LN TO CM_INVOICE_DATA_LN_BAK';
    EXECUTE IMMEDIATE 'RENAME CM_INV_DATA_LN_BCL TO CM_INV_DATA_LN_BCL_BAK';
    EXECUTE IMMEDIATE 'RENAME CM_INV_DATA_LN_RATE TO CM_INV_DATA_LN_RATE_BAK';
    EXECUTE IMMEDIATE 'RENAME CM_INV_DATA_LN_SVC_QTY TO CM_INV_DATA_LN_SVC_QTY_BAK';
    EXECUTE IMMEDIATE 'RENAME CM_INV_DATA_TAX TO CM_INV_DATA_TAX_BAK';
    EXECUTE IMMEDIATE 'RENAME CM_INV_DATA_ADJ TO CM_INV_DATA_ADJ_BAK';
    EXECUTE IMMEDIATE 'RENAME CM_INV_DATA_EXCP TO CM_INV_DATA_EXCP_BAK';
    EXECUTE IMMEDIATE 'RENAME CM_PAY_REQ TO CM_PAY_REQ_BAK';
    EXECUTE IMMEDIATE 'RENAME CM_PAY_REQ_GRANULARITIES TO CM_PAY_REQ_GRANULARITIES_BAK';
    EXECUTE IMMEDIATE 'RENAME CM_NON_TRANS_PRICE TO CM_NON_TRANS_PRICE_BAK';
    EXECUTE IMMEDIATE 'RENAME CM_BILL_ID_MAP TO CM_BILL_ID_MAP_BAK';

    EXECUTE IMMEDIATE 'DROP SYNONYM ODI_WORK.CM_INVOICE_DATA';
    EXECUTE IMMEDIATE 'DROP SYNONYM ODI_WORK.CM_INVOICE_DATA_LN';
    EXECUTE IMMEDIATE 'DROP SYNONYM ODI_WORK.CM_INV_DATA_LN_BCL';
    EXECUTE IMMEDIATE 'DROP SYNONYM ODI_WORK.CM_INV_DATA_LN_RATE';
    EXECUTE IMMEDIATE 'DROP SYNONYM ODI_WORK.CM_INV_DATA_LN_SVC_QTY';
    EXECUTE IMMEDIATE 'DROP SYNONYM ODI_WORK.CM_INV_DATA_TAX';
    EXECUTE IMMEDIATE 'DROP SYNONYM ODI_WORK.CM_INV_DATA_ADJ';
    EXECUTE IMMEDIATE 'DROP SYNONYM ODI_WORK.CM_INV_DATA_EXCP';
    EXECUTE IMMEDIATE 'DROP SYNONYM ODI_WORK.CM_PAY_REQ';
    EXECUTE IMMEDIATE 'DROP SYNONYM ODI_WORK.CM_PAY_REQ_GRANULARITIES';
    EXECUTE IMMEDIATE 'DROP SYNONYM IF112_DBLINK_APPUSER.CM_NON_TRANS_PRICE';
    EXECUTE IMMEDIATE 'DROP SYNONYM IF112_DBLINK_APPUSER.CM_BILL_ID_MAP';

EXCEPTION
    WHEN OTHERS THEN
        IF sqlcode != -04043 THEN
            RAISE;
        END IF;

END;
/

create or replace synonym cbe_mam_owner.CM_INVOICE_DATA for cisadm.CM_INVOICE_DATA_BAK;
create or replace synonym cbe_mam_owner.CM_INVOICE_DATA_LN for cisadm.CM_INVOICE_DATA_LN_BAK;
create or replace synonym cbe_mam_owner.CM_INV_DATA_TAX for cisadm.CM_INV_DATA_TAX_BAK;
create or replace synonym cbe_mam_owner.CM_PAY_REQ for cisadm.CM_PAY_REQ_BAK;

create or replace synonym cbe_mam_appuser.CM_INVOICE_DATA for cisadm.CM_INVOICE_DATA_BAK;
create or replace synonym cbe_mam_appuser.CM_INVOICE_DATA_LN for cisadm.CM_INVOICE_DATA_LN_BAK;
create or replace synonym cbe_mam_appuser.CM_INV_DATA_TAX for cisadm.CM_INV_DATA_TAX_BAK;
create or replace synonym cbe_mam_appuser.CM_PAY_REQ for cisadm.CM_PAY_REQ_BAK;
