CREATE TABLE SUB_ACCT (
  SUB_ACCT_ID VARCHAR2 (30) NOT NULL,
  ACCT_ID VARCHAR2 (30) NOT NULL,
  SUB_ACCT_TYPE VARCHAR2 (15) NOT NULL,
  STATUS VARCHAR2 (15) NOT NULL,
  VALID_FROM DATE NOT NULL,
  VALID_TO DATE,
  CRE_DTTM DATE NOT NULL,
  LAST_UPD_DTTM DATE NOT NULL,
  CONSTRAINT SUB_ACCT_ACCT_FK FOREIGN KEY (ACCT_ID) REFERENCES ACCT(ACCT_ID)
);