
  CREATE TABLE PARTY_HIER
   (PARENT_PARTY_ID VARCHAR2(16 BYTE)       NOT NULL ENABLE,
    CHILD_PARTY_ID VARCHAR2(16 BYTE)        NOT NULL ENABLE,
    PARTY_HIER_TYPE VARCHAR2(50 BYTE)       NOT NULL ENABLE,
    STATUS VARCHAR2(20 BYTE)                NOT NULL ENABLE,
    VALID_FROM DATE,
	  VALID_TO DATE,
    CRE_DTTM TIMESTAMP                      NOT NULL ENABLE,
	  LAST_UPD_DTTM TIMESTAMP,
    BATCH_CODE VARCHAR2(128 BYTE)           NOT NULL ENABLE,
    BATCH_ATTEMPT NUMBER(3, 0)              NOT NULL ENABLE,
    ILM_DT TIMESTAMP  				              NOT NULL ENABLE,
    ILM_ARCH_SW CHAR(1)           		      NOT NULL ENABLE,
    PARTITION_ID NUMBER(5,0)          	    GENERATED ALWAYS AS (ORA_HASH(PARENT_PARTY_ID || CHILD_PARTY_ID, 15)) VIRTUAL,
  CONSTRAINT "PK_PARTY_HIER" PRIMARY KEY ("CHILD_PARTY_ID")
)
TABLESPACE CBE_MDU_DATA
    PARTITION BY RANGE (ILM_DT) INTERVAL(NUMTODSINTERVAL(1, 'DAY'))
SUBPARTITION BY LIST(PARTITION_ID)
SUBPARTITION TEMPLATE(
    SUBPARTITION p1 VALUES(0,1,2,3),
    SUBPARTITION p2 VALUES(4,5,6,7),
    SUBPARTITION p3 VALUES(8,9,10,11),
    SUBPARTITION p4 VALUES(12,13,14,15))
(PARTITION before_2021 VALUES LESS THAN (TO_DATE('01-JAN-2021', 'dd-MON-yyyy')));