DROP TABLE ACCT;

  CREATE TABLE ACCT
   (ACCT_ID VARCHAR2(60 BYTE)              NOT NULL ENABLE,
    PARTY_ID VARCHAR2(16 BYTE)             NOT NULL ENABLE,
    ACCT_TYPE VARCHAR2(4 BYTE)             NOT NULL ENABLE,
    LCP VARCHAR2(16 BYTE)                  NOT NULL ENABLE,
    CURRENCY_CD CHAR(3 BYTE)               NOT NULL ENABLE,
    STATUS VARCHAR2(20 BYTE)               NOT NULL ENABLE,
    BILL_CYC_ID CHAR(4)                    NOT NULL ENABLE,
    PROCESSING_GRP VARCHAR2(50 BYTE),
	  VALID_FROM DATE,
	  VALID_TO DATE,
    CRE_DTTM TIMESTAMP                      NOT NULL ENABLE,
	  LAST_UPD_DTTM TIMESTAMP,
    BATCH_CODE VARCHAR2(128 BYTE)           NOT NULL ENABLE,
    BATCH_ATTEMPT NUMBER(3, 0)              NOT NULL ENABLE,
    ILM_DT TIMESTAMP  				              NOT NULL ENABLE,
    ILM_ARCH_SW CHAR(1)           		      NOT NULL ENABLE,
    PARTITION_ID NUMBER(5,0)          	    GENERATED ALWAYS AS (ORA_HASH(ACCT_ID, 15)) VIRTUAL,
  CONSTRAINT "PK_ACCT" PRIMARY KEY ("ACCT_ID")
)
TABLESPACE CBE_MDU_DATA
    PARTITION BY RANGE (ILM_DT) INTERVAL(NUMTODSINTERVAL(1, 'DAY'))
SUBPARTITION BY LIST(PARTITION_ID)
SUBPARTITION TEMPLATE(
    SUBPARTITION p1 VALUES(0,1,2,3),
    SUBPARTITION p2 VALUES(4,5,6,7),
    SUBPARTITION p3 VALUES(8,9,10,11),
    SUBPARTITION p4 VALUES(12,13,14,15))
(PARTITION before_2021 VALUES LESS THAN (TO_DATE('01-JAN-2021', 'dd-MON-yyyy')));