CREATE TABLE ACCT_HIER (
  PARENT_ACCT_PARTY_ID VARCHAR2 (30) NOT NULL,
  PARENT_ACCT_ID VARCHAR2 (30) NOT NULL,
  CHILD_ACCT_PARTY_ID VARCHAR2 (30) NOT NULL,
  CHILD_ACCT_ID VARCHAR2 (30) NOT NULL,
  STATUS VARCHAR2 (15) NOT NULL,
  VALID_FROM DATE NOT NULL,
  VALID_TO DATE,
  CRE_DTTM DATE NOT NULL,
  LAST_UPD_DTTM DATE NOT NULL,
  CONSTRAINT HIER_ACCT_PARENT_FK FOREIGN KEY (PARENT_ACCT_ID) REFERENCES ACCT(ACCT_ID),
  CONSTRAINT HIER_ACCT_CHILD_FK FOREIGN KEY (CHILD_ACCT_ID) REFERENCES ACCT(ACCT_ID)
);