----Need to change the date values according to run date--
select * from ( 
select	
	CM_PAY_REQ.BILL_ID	BILL_ID,
	CM_PAY_REQ.PER_ID_NBR	PER_ID_NBR,
	CM_PAY_REQ.CIS_DIVISION	CIS_DIVISION,
	CM_PAY_REQ.LINE_ID	LINE_ID,
	CM_PAY_REQ.ALT_BILL_ID	ALT_BILL_ID,
	CM_PAY_REQ.BILL_DT	BILL_DT,
	CM_PAY_REQ.ACCT_TYPE	ACCT_TYPE,
	CM_PAY_REQ.PAY_TYPE	PAY_TYPE,
	CM_PAY_REQ.BILL_AMT	BILL_AMT,
	CM_PAY_REQ.CURRENCY_CD	CURRENCY_CD,
	CM_PAY_REQ.IS_IND_FLG	IS_IND_FLG,
	CM_PAY_REQ.SUB_STLMNT_LVL	SUB_STLMNT_LVL,
	CM_PAY_REQ.SUB_STLMNT_LVL_REF	SUB_STLMNT_LVL_REF,
	CM_PAY_REQ.CR_NOTE_FR_BILL_ID	CR_NOTE_FR_BILL_ID,
	CM_PAY_REQ.IS_IMD_FIN_ADJ	IS_IMD_FIN_ADJ,
	CM_PAY_REQ.FIN_ADJ_MAN_NRT	FIN_ADJ_MAN_NRT,
	CM_PAY_REQ.REL_RSRV_FLG	REL_RSRV_FLG,
	CM_PAY_REQ.REL_WAF_FLG	REL_WAF_FLG,
	CM_PAY_REQ.FASTEST_ROUTE_INDICATOR	FASTEST_ROUTE_INDICATOR,
	CM_PAY_REQ.CASE_IDENTIFIER	CASE_IDENTIFIER,
	CM_PAY_REQ.PAY_REQ_GRANULARITIES	PAY_REQ_GRANULARITIES,
	CM_PAY_REQ.CREATE_DTTM	CREATE_DTTM,
	CM_PAY_REQ.UPLOAD_DTTM	UPLOAD_DTTM,
	CM_PAY_REQ.EXTRACT_FLG	EXTRACT_FLG,
	CM_PAY_REQ.EXTRACT_DTTM	EXTRACT_DTTM,
	CM_PAY_REQ.REUSE_DUE_DT	REUSE_DUE_DT,
	CM_PAY_REQ.INV_RECALC_FLG	INV_RECALC_FLG,
	CM_PAY_REQ.OVERPAYMENT_FLG	OVERPAYMENT_FLG,
	CM_PAY_REQ.PAY_DETAIL_ID	PAY_DETAIL_ID,
	CM_PAY_REQ.SETT_LEVEL_GRANULARITY	SETT_LEVEL_GRANULARITY
from	ODI_WORK.CM_PAY_REQ CM_PAY_REQ
where	(1=1)
 and (CM_PAY_REQ.ILM_DT  between to_date(:startDate,'yyyy mm dd HH24:MI:SS') and to_date(:endDate,'yyyy mm dd HH24:MI:SS'))
)