---Change the Date value according to run date ----
select * from (
select
	CM_PAY_REQ_GRANULARITIES.BILL_ID	BILL_ID,
	CM_PAY_REQ_GRANULARITIES.LINE_ID	LINE_ID,
	CM_PAY_REQ_GRANULARITIES.GRANULARITIES_TYPE	GRANULARITIES_TYPE,
	CM_PAY_REQ_GRANULARITIES.REFERENCE_VAL	REFERENCE_VAL,
	CM_PAY_REQ_GRANULARITIES.UPLOAD_DTTM	UPLOAD_DTTM,
	CM_PAY_REQ_GRANULARITIES.EXTRACT_FLG	EXTRACT_FLG,
	CM_PAY_REQ_GRANULARITIES.EXTRACT_DTTM	EXTRACT_DTTM,
	CM_PAY_REQ_GRANULARITIES.PAY_DETAIL_ID	PAY_DETAIL_ID
from	ODI_WORK.CM_PAY_REQ_GRANULARITIES CM_PAY_REQ_GRANULARITIES
where	(1=1)
 and (CM_PAY_REQ_GRANULARITIES.UPLOAD_DTTM >= to_date(:startDate,'yyyy mm dd HH24:MI:SS') and
CM_PAY_REQ_GRANULARITIES.UPLOAD_DTTM < to_date(:endDate,'yyyy mm dd HH24:MI:SS'))
)